"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.

"""

a, b = 1, 1
total = 0

while a <= 4000000:
    if a % 2 == 0:
        total += a
        print(a)
    a, b = b, a + b

print(total)


def fibonacci(n):
    a = 1
    b = 1
    for i in range(0, n):
        temp = a
        a = b
        b = temp + b
    return a

a = fibonacci(40000000)
print(a)